spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/security?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/changelog.xml

security:
  jwt:
    secret-key: bWlrZWhlbnJ5LXNlY3VyaXR5LWRldi1zZWNyZXQta2V5
    token-validity-in-seconds: 3600